-- Gebiete sind Landkreise und kreisfreie Städte (Malcolm, 2026-10-09). Zulassung und Geschlechterbalance gelten im
-- Landkreis, in dem man wohnt; die Vorschläge richten sich weiter nur nach dem eigenen Umkreis. Die Grenzen lädt
-- scripts/load-districts.mjs (BKG, © GeoBasis-DE / BKG, dl-de/by-2-0) über load_districts().
-- Gebiete ohne Umriss (z. B. aus Lasttests oder bevor die Grenzen geladen sind) gelten weiter per Radius.

alter table areas add column code text unique;

create table area_shapes (
  id bigint generated by default as identity primary key,
  area_id bigint not null references areas on delete cascade,
  shape polygon not null,
  size double precision not null
);
create index area_shapes_area on area_shapes (area_id);
create index area_shapes_shape on area_shapes using gist (shape);
alter table area_shapes enable row level security;
revoke all on area_shapes from anon, authenticated;

-- Das Beta-Gebiet Gießen wird zum Landkreis Gießen; Name, Mitglieder und Events bleiben.
update areas set code = '06531' where name = 'Gießen' and code is null;

-- Liegt ein Punkt in mehreren Umrissen (kreisfreie Stadt mitten im Landkreis), gilt der kleinste.
create function area_for(p_lat double precision, p_lng double precision) returns bigint
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select area_id from area_shapes where shape @> point(p_lng, p_lat) order by size limit 1),
    (select a.id from areas a
     where not exists (select from area_shapes s where s.area_id = a.id)
       and distance_km(p_lat, p_lng, a.lat, a.lng) <= a.radius_km
     order by distance_km(p_lat, p_lng, a.lat, a.lng) limit 1))
$$;

-- districts: [{code, name, lat, lng, shapes: [{points: '((lng,lat),…)', size}]}]. Vorhandene Gebiete behalten
-- Name und Kapazität, nur die Umrisse werden ersetzt.
create function load_districts(districts jsonb, capacity int) returns int
language plpgsql security definer set search_path = public as $$
declare
  d jsonb;
  aid bigint;
  n int := 0;
begin
  for d in select * from jsonb_array_elements(districts) loop
    insert into areas (code, name, lat, lng, capacity)
      values (d->>'code', d->>'name', (d->>'lat')::float8, (d->>'lng')::float8, load_districts.capacity)
      on conflict (code) do nothing;
    select id into aid from areas where code = d->>'code';
    delete from area_shapes where area_id = aid;
    insert into area_shapes (area_id, shape, size)
      select aid, (s->>'points')::polygon, (s->>'size')::float8 from jsonb_array_elements(d->'shapes') s;
    n := n + 1;
  end loop;
  return n;
end $$;

-- Testbetrieb: im eigenen Landkreis zulassen, sonst im nächstgelegenen Gebiet.
create or replace function beta_verify() returns void
language plpgsql security definer set search_path = public as $$
declare me profiles;
begin
  if not beta_enabled() then raise exception 'beta disabled' using errcode = 'insufficient_privilege'; end if;
  select * into me from profiles where id = auth.uid();
  if me.id is null then raise exception 'no profile' using errcode = 'check_violation'; end if;
  insert into verifications (user_id, provider, provider_ref, id_check, selfie_match, decided_at)
    values (me.id, 'beta', 'beta', 'passed', 'passed', now()) on conflict do nothing;
  update profiles set status = 'admitted',
    area_id = coalesce(area_for(me.lat, me.lng), (select id from areas order by distance_km(me.lat, me.lng, lat, lng) limit 1))
  where id = me.id and status = 'pending_verification';
end $$;

revoke execute on function area_for, load_districts from public, anon, authenticated;
grant execute on function area_for, load_districts to service_role;
