-- Date-Check (Regeln wie src/domain/dateCheck.ts): Vor einem Date wählt man eine Vertrauensperson. Sie bekommt
-- einen privaten Link und sieht dort, mit wem man sich wo trifft, und solange der Check läuft, den Standort.
-- Nach einer Stunde fragt die App „Alles okay?“. Wer um Hilfe bittet oder 15 Minuten nicht antwortet, für den
-- schickt der Server der Vertrauensperson eine SMS (Edge Function date-alarm). Meldet man sich danach doch,
-- kommt eine Entwarnung. Nach 12 Stunden endet jeder Check, und der Standort wird gelöscht.

create table date_checks (
  id bigint generated by default as identity primary key,
  token text not null unique default replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
  user_id uuid not null references profiles on delete cascade,
  match_id bigint not null references matches on delete cascade,
  contact_name text not null check (length(trim(contact_name)) between 1 and 40),
  contact_phone text not null check (contact_phone ~ '^\+[1-9][0-9]{7,14}$'),
  status text not null default 'active' check (status in ('active', 'help', 'ended')),
  check_at timestamptz not null default now() + interval '1 hour',
  lat double precision,
  lng double precision,
  located_at timestamptz,
  -- Zuletzt verschickte SMS: overdue (keine Antwort), help (Hilferuf), clear (Entwarnung) oder noch keine.
  alarm_sent text check (alarm_sent in ('overdue', 'help', 'clear')),
  created_at timestamptz not null default now(),
  ended_at timestamptz
);
create index date_checks_user on date_checks (user_id, created_at);
create index date_checks_open on date_checks (check_at) where status <> 'ended';
alter table date_checks enable row level security;
revoke all on date_checks from anon, authenticated;

-- Server-Einstellungen, die der Beta-Workflow setzt (z. B. die Adresse der Alarm-Funktion).
create table app_settings (key text primary key, value text not null);
alter table app_settings enable row level security;
revoke all on app_settings from anon, authenticated;

create function date_check_overdue(c date_checks) returns boolean
language sql stable as $$ select c.status = 'active' and now() > c.check_at + interval '15 minutes' $$;

create function my_date_check(p_token text) returns date_checks
language plpgsql stable security definer set search_path = public as $$
declare c date_checks;
begin
  select * into c from date_checks where token = p_token and user_id = auth.uid() and status <> 'ended'
    and created_at > now() - interval '12 hours';
  if c.id is null then raise exception 'no date check' using errcode = 'insufficient_privilege'; end if;
  return c;
end $$;

-- Startet den Check für das Date mit einem Match. Höchstens 3 pro Tag, weil jeder Check SMS auslösen kann.
create function start_date_check(other uuid, contact_name text, contact_phone text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  m matches := match_with(other);
  c date_checks;
begin
  if not exists (select from match_dates where match_id = m.id and accepted and not past) then
    raise exception 'no date' using errcode = 'check_violation';
  end if;
  if (select count(*) from date_checks where user_id = auth.uid() and created_at > now() - interval '1 day') >= 3 then
    raise exception 'too many date checks' using errcode = 'check_violation';
  end if;
  update date_checks set status = 'ended', ended_at = now(), lat = null, lng = null
    where user_id = auth.uid() and match_id = m.id and status <> 'ended';
  insert into date_checks (user_id, match_id, contact_name, contact_phone)
    values (auth.uid(), m.id, trim(contact_name), contact_phone) returning * into c;
  return jsonb_build_object('token', c.token, 'check_at', c.check_at, 'status', c.status, 'contact_name', c.contact_name);
end $$;

-- Der laufende Check für das Date mit einem Match, sonst null.
create function current_date_check(other uuid) returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object('token', c.token, 'check_at', c.check_at, 'status', c.status,
                            'contact_name', c.contact_name, 'overdue', date_check_overdue(c))
  from date_checks c
  where c.user_id = auth.uid() and c.match_id = (match_with(other)).id
    and c.status <> 'ended' and c.created_at > now() - interval '12 hours'
  order by c.created_at desc limit 1
$$;

create function date_check_location(p_token text, lat double precision, lng double precision) returns void
language plpgsql security definer set search_path = public as $$
declare c date_checks := my_date_check(p_token);
begin
  update date_checks set lat = date_check_location.lat, lng = date_check_location.lng, located_at = now() where id = c.id;
end $$;

-- ok: alles gut, Check endet und der Standort wird gelöscht. later: noch eine Stunde. help: Hilferuf.
create function answer_date_check(p_token text, answer text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare c date_checks := my_date_check(p_token);
begin
  if answer = 'ok' then
    update date_checks set status = 'ended', ended_at = now(), lat = null, lng = null where id = c.id;
  elsif answer = 'later' then
    if c.status = 'help' then raise exception 'help requested' using errcode = 'check_violation'; end if;
    update date_checks set check_at = greatest(check_at, now()) + interval '1 hour' where id = c.id;
  elsif answer = 'help' then
    update date_checks set status = 'help' where id = c.id;
  else
    raise exception 'unknown answer' using errcode = 'check_violation';
  end if;
  select * into c from date_checks where id = c.id;
  return jsonb_build_object('token', c.token, 'check_at', c.check_at, 'status', c.status,
                            'contact_name', c.contact_name, 'overdue', date_check_overdue(c));
end $$;

-- Für die Seite der Vertrauensperson (ohne Anmeldung, nur mit dem Link). Nach dem Ende ohne Standort.
create function date_check_public(p_token text) returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'name', me.display_name,
    'photo', me.photos[1],
    'match', jsonb_build_object('name', o.display_name, 'age', date_part('year', age(o.birthdate))::int, 'photo', o.photos[1]),
    'place', d.place,
    'when', d.when_text,
    'status', case when c.status = 'ended' or c.created_at < now() - interval '12 hours' then 'ended'
                   when c.status = 'help' then 'help'
                   when date_check_overdue(c) then 'overdue' else 'active' end,
    'check_at', c.check_at,
    'location', case when c.status <> 'ended' and c.created_at > now() - interval '12 hours' and c.lat is not null
                     then jsonb_build_object('lat', c.lat, 'lng', c.lng, 'at', c.located_at) end)
  from date_checks c
  join profiles me on me.id = c.user_id
  join matches m on m.id = c.match_id
  join profiles o on o.id = case when m.user_a = c.user_id then m.user_b else m.user_a end
  left join match_dates d on d.match_id = m.id
  where c.token = p_token
$$;

-- Für die Alarm-Funktion: fällige SMS reservieren, damit keine doppelt rausgeht. Schlägt das Senden fehl,
-- gibt release_date_alarm die Reservierung zurück.
create function claim_date_alarms() returns table (id bigint, kind text, previous text, contact_phone text, contact_name text, user_name text, token text)
language plpgsql security definer set search_path = public as $$
begin
  return query
  with due as (
    select c.id, c.alarm_sent as previous,
      case
        when c.status = 'help' and c.alarm_sent is distinct from 'help' then 'help'
        when date_check_overdue(c) and c.alarm_sent is null then 'overdue'
        when c.alarm_sent in ('overdue', 'help') and (c.status = 'ended' or (c.status = 'active' and not date_check_overdue(c))) then 'clear'
      end as kind
    from date_checks c
    where c.created_at > now() - interval '12 hours'
    for update skip locked
  ),
  claimed as (
    update date_checks c set alarm_sent = d.kind
    from due d where c.id = d.id and d.kind is not null
    returning c.id, d.kind, d.previous, c.contact_phone, c.contact_name, c.user_id, c.token
  )
  select x.id, x.kind, x.previous, x.contact_phone, x.contact_name, p.display_name, x.token
  from claimed x join profiles p on p.id = x.user_id;
  -- Nach einer Entwarnung zählt ein späteres Überziehen wieder als neuer Alarm.
  update date_checks c set alarm_sent = null where c.alarm_sent = 'clear' and c.status = 'active';
end $$;

create function release_date_alarm(p_id bigint, p_previous text) returns void
language sql security definer set search_path = public as $$
  update date_checks set alarm_sent = p_previous where id = p_id
$$;

-- Jede Minute: abgelaufene Checks beenden (Standort weg) und, wenn eine SMS fällig ist, die Alarm-Funktion anstoßen.
create function date_check_tick() returns void
language plpgsql security definer set search_path = public as $$
declare url text := (select value from app_settings where key = 'date_alarm_url');
begin
  update date_checks set status = 'ended', ended_at = now(), lat = null, lng = null
    where status <> 'ended' and created_at < now() - interval '12 hours';
  if url is not null and exists (
    select from date_checks c where c.created_at > now() - interval '12 hours' and (
      (c.status = 'help' and c.alarm_sent is distinct from 'help')
      or (date_check_overdue(c) and c.alarm_sent is null)
      or (c.alarm_sent in ('overdue', 'help') and (c.status = 'ended' or (c.status = 'active' and not date_check_overdue(c))))))
  then
    perform net.http_post(url := url, body := '{}'::jsonb);
  end if;
end $$;

revoke execute on function date_check_overdue, my_date_check, start_date_check, current_date_check, date_check_location,
  answer_date_check, date_check_public, claim_date_alarms, release_date_alarm, date_check_tick from public, anon, authenticated;
grant execute on function start_date_check, current_date_check, date_check_location, answer_date_check to authenticated;
grant execute on function date_check_public to anon, authenticated;
grant execute on function claim_date_alarms, release_date_alarm to service_role;

-- Zeitplan nur auf Supabase (pg_cron und pg_net gibt es in den lokalen Tests nicht).
do $do$
begin
  if not exists (select from pg_available_extensions where name = 'pg_cron')
     or not exists (select from pg_available_extensions where name = 'pg_net') then return; end if;
  create extension if not exists pg_net;
  create extension if not exists pg_cron;
  perform cron.schedule('date-check-tick', '* * * * *', 'select public.date_check_tick()');
end $do$;
