-- Echt: Grundschema. Grenzwerte spiegeln src/domain (activity.ts, dailyPicks.ts).

create table areas (
  id bigint generated by default as identity primary key,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  radius_km int not null default 30,
  capacity int not null
);

create table profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text not null,
  birthdate date not null,
  gender text not null check (gender in ('f', 'm')),
  seeking text[] not null check (seeking <@ array['f', 'm']),
  bio text not null default '',
  lat double precision not null,
  lng double precision not null,
  area_id bigint references areas,
  status text not null default 'pending_verification'
    check (status in ('pending_verification', 'waitlisted', 'admitted', 'rejected')),
  last_active_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Nur das Ergebnis der Prüfung, keine Ausweis- oder Selfie-Bilder.
create table verifications (
  user_id uuid primary key references auth.users on delete cascade,
  provider text not null,
  provider_ref text not null,
  id_check text not null check (id_check in ('passed', 'failed', 'pending')),
  selfie_match text not null check (selfie_match in ('passed', 'failed', 'pending')),
  decided_at timestamptz
);

create table likes (
  from_id uuid not null references profiles on delete cascade,
  to_id uuid not null references profiles on delete cascade,
  decision text not null check (decision in ('like', 'pass')),
  created_at timestamptz not null default now(),
  primary key (from_id, to_id),
  check (from_id <> to_id)
);

create table matches (
  id bigint generated by default as identity primary key,
  user_a uuid not null references profiles on delete cascade,
  user_b uuid not null references profiles on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_a, user_b),
  check (user_a < user_b)
);

create table reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users on delete cascade,
  reported_id uuid not null references profiles on delete cascade,
  reason text not null,
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_at timestamptz not null default now(),
  unique (reporter_id, reported_id)
);

-- Regeln ---------------------------------------------------------------

create function distance_km(lat1 float8, lng1 float8, lat2 float8, lng2 float8) returns float8
language sql immutable as $$
  select 2 * 6371 * asin(sqrt(
    power(sin(radians(lat2 - lat1) / 2), 2) +
    cos(radians(lat1)) * cos(radians(lat2)) * power(sin(radians(lng2 - lng1) / 2), 2)))
$$;

-- activity.ts: nach 7 Tagen versteckt, ab 3 offenen Meldungen gesperrt
create function is_discoverable(p profiles) returns boolean
language sql stable security definer set search_path = public as $$
  select p.status = 'admitted'
     and p.last_active_at > now() - interval '7 days'
     and (select count(*) from reports r where r.reported_id = p.id and r.status = 'open') < 3
$$;

create function day_start() returns timestamptz language sql stable as
$$ select date_trunc('day', now() at time zone 'Europe/Berlin') at time zone 'Europe/Berlin' $$;

-- Sichten (laufen mit Rechten des Eigentümers, filtern selbst nach auth.uid()) --

create view public_profiles as
  select t.id, t.display_name, date_part('year', age(t.birthdate))::int as age, t.gender, t.bio,
         round(distance_km(me.lat, me.lng, t.lat, t.lng))::int as distance_km
  from profiles me
  join areas a on a.id = me.area_id
  join profiles t on t.id <> me.id
  where me.id = auth.uid()
    and is_discoverable(me)
    and is_discoverable(t)
    and t.gender = any(me.seeking) and me.gender = any(t.seeking)
    and distance_km(me.lat, me.lng, t.lat, t.lng) <= a.radius_km
    and not exists (select from likes l where l.from_id = me.id and l.to_id = t.id);

create view my_picks_today as
  select count(*)::int as used, greatest(0, 6 - count(*))::int as remaining
  from likes where from_id = auth.uid() and created_at >= day_start();

create view my_waitlist_position as
  select position from (
    select id, rank() over (partition by area_id order by created_at)::int as position
    from profiles where status = 'waitlisted'
  ) w where id = auth.uid();

-- activity.ts: nach 14 Tagen pausiert, der Platz wird frei
create view area_stats as
  select a.id as area_id, a.capacity,
         count(p.id) filter (where p.gender = 'f')::int as f,
         count(p.id) filter (where p.gender = 'm')::int as m
  from areas a
  left join profiles p on p.area_id = a.id and p.status = 'admitted'
                      and p.last_active_at > now() - interval '14 days'
  group by a.id;

-- Trigger ----------------------------------------------------------------

create function enforce_daily_limit() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if (select count(*) from likes where from_id = new.from_id and created_at >= day_start()) >= 6 then
    raise exception 'daily limit reached' using errcode = 'check_violation';
  end if;
  return new;
end $$;

create trigger likes_daily_limit before insert on likes
  for each row execute function enforce_daily_limit();

create function create_match() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.decision = 'like' and exists (
    select from likes where from_id = new.to_id and to_id = new.from_id and decision = 'like'
  ) then
    insert into matches (user_a, user_b)
      values (least(new.from_id, new.to_id), greatest(new.from_id, new.to_id))
      on conflict do nothing;
  end if;
  return new;
end $$;

create trigger likes_create_match after insert on likes
  for each row execute function create_match();

create function touch_activity() returns void
language sql security definer set search_path = public as
$$ update profiles set last_active_at = now() where id = auth.uid() $$;

-- Zugriff ----------------------------------------------------------------

alter table areas enable row level security;
alter table profiles enable row level security;
alter table verifications enable row level security;
alter table likes enable row level security;
alter table matches enable row level security;
alter table reports enable row level security;

revoke all on areas, profiles, verifications, likes, matches, reports from anon, authenticated;
revoke all on public_profiles, my_picks_today, my_waitlist_position, area_stats from anon, authenticated;
revoke execute on function is_discoverable, enforce_daily_limit, create_match, touch_activity from public;

grant select on areas, area_stats, public_profiles, my_picks_today, my_waitlist_position to authenticated;
-- Funktionen in Sichten werden mit den Rechten der aufrufenden Person geprüft.
grant execute on function touch_activity, is_discoverable to authenticated;

create policy "areas lesbar" on areas for select to authenticated using (true);

grant select, insert (id, display_name, birthdate, gender, seeking, bio, lat, lng),
  update (display_name, seeking, bio, lat, lng) on profiles to authenticated;
create policy "eigenes Profil" on profiles for all to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

grant select, insert (from_id, to_id, decision) on likes to authenticated;
create policy "eigene Entscheidungen lesen" on likes for select to authenticated using (from_id = auth.uid());
create policy "nur sichtbare Profile liken" on likes for insert to authenticated
  with check (from_id = auth.uid() and to_id in (select id from public_profiles));

grant select on matches to authenticated;
create policy "eigene Matches" on matches for select to authenticated
  using (auth.uid() in (user_a, user_b));

grant insert (reporter_id, reported_id, reason) on reports to authenticated;
create policy "im eigenen Namen melden" on reports for insert to authenticated
  with check (reporter_id = auth.uid());
