-- Nach dem Match: Fragenrunde in 3 Stufen, Chat, Date-Vorschlag, Check danach, freundlich beenden
-- (Regeln wie src/domain/conversation.ts). Die App liest alles über my_matches() und schreibt nur über
-- die Funktionen unten; direkt auf die Tabellen hat niemand Zugriff.

alter table matches add column ended_by uuid references profiles on delete set null, add column ended_at timestamptz;

-- Schlüssel wie answerKey(): Runde-Frage, 3 Runden mit je 2 Fragen.
create table match_answers (
  match_id bigint not null references matches on delete cascade,
  user_id uuid not null references profiles on delete cascade,
  question_key text not null check (question_key in ('0-0', '0-1', '1-0', '1-1', '2-0', '2-1')),
  answer text not null check (length(trim(answer)) between 1 and 500),
  created_at timestamptz not null default now(),
  primary key (match_id, user_id, question_key)
);

create table messages (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches on delete cascade,
  sender_id uuid not null references profiles on delete cascade,
  body text not null check (length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);
create index messages_match on messages (match_id, created_at);

create table match_dates (
  match_id bigint primary key references matches on delete cascade,
  proposed_by uuid not null references profiles on delete cascade,
  idea text,
  place text not null,
  when_text text not null,
  reserved boolean not null default false,
  accepted boolean not null default false,
  past boolean not null default false,
  created_at timestamptz not null default now()
);

create table after_date (
  match_id bigint not null references matches on delete cascade,
  user_id uuid not null references profiles on delete cascade,
  answer text not null check (answer in ('yes', 'no')),
  primary key (match_id, user_id)
);

alter table match_answers enable row level security;
alter table messages enable row level security;
alter table match_dates enable row level security;
alter table after_date enable row level security;
revoke all on match_answers, messages, match_dates, after_date from anon, authenticated;

-- Hilfsfunktionen ----------------------------------------------------------

-- Das gemeinsame Match mit einer anderen Person, sonst Fehler.
create function match_with(other uuid) returns matches
language plpgsql stable security definer set search_path = public as $$
declare m matches;
begin
  select * into m from matches
  where user_a = least(auth.uid(), other) and user_b = greatest(auth.uid(), other);
  if m.id is null then raise exception 'no match' using errcode = 'insufficient_privilege'; end if;
  return m;
end $$;

-- Eine Runde ist fertig, wenn beide alle Fragen der Runde beantwortet haben.
create function round_done(p_match bigint, p_round int) returns boolean
language sql stable security definer set search_path = public as $$
  select count(*) = 4 from match_answers where match_id = p_match and question_key like p_round || '-%'
$$;

create function chat_open(p_match bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select round_done(p_match, 0) and round_done(p_match, 1) and round_done(p_match, 2)
$$;

-- Lesen --------------------------------------------------------------------

-- Alle eigenen Matches mit Verlauf. Die Antwort der anderen Person gibt es erst nach der eigenen,
-- beim Check nach dem Date ebenso.
create function my_matches() returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(m order by last_at desc), '[]') from (
    select greatest(x.created_at, (select max(created_at) from messages where match_id = x.id)) as last_at,
      jsonb_build_object(
        'id', o.id,
        'name', o.display_name,
        'age', date_part('year', age(o.birthdate))::int,
        'prompts', o.prompts,
        'interests', o.interests,
        'ended', x.ended_at is not null,
        'answers', (
          select coalesce(jsonb_object_agg(mine.question_key, jsonb_build_object('mine', mine.answer, 'theirs', theirs.answer)), '{}')
          from match_answers mine
          left join match_answers theirs on theirs.match_id = x.id and theirs.user_id = o.id and theirs.question_key = mine.question_key
          where mine.match_id = x.id and mine.user_id = auth.uid()),
        'messages', (
          select coalesce(jsonb_agg(jsonb_build_object('id', id, 'mine', sender_id = auth.uid(), 'text', body, 'at', created_at) order by created_at, id), '[]')
          from messages where match_id = x.id),
        'date', (
          select jsonb_build_object('idea', idea, 'place', place, 'when', when_text, 'reserved', reserved,
                                    'accepted', accepted, 'past', past, 'mine', proposed_by = auth.uid())
          from match_dates where match_id = x.id),
        'after_date', (
          select jsonb_build_object('mine', mine.answer, 'theirs', theirs.answer)
          from after_date mine
          left join after_date theirs on theirs.match_id = x.id and theirs.user_id = o.id
          where mine.match_id = x.id and mine.user_id = auth.uid())
      ) as m
    from matches x
    join profiles o on o.id = case when x.user_a = auth.uid() then x.user_b else x.user_a end
    where auth.uid() in (x.user_a, x.user_b)
  ) s
$$;

-- Schreiben ----------------------------------------------------------------

create function answer_question(other uuid, question_key text, answer text) returns void
language plpgsql security definer set search_path = public as $$
declare
  m matches := match_with(other);
  r int := split_part(question_key, '-', 1)::int;
begin
  if m.ended_at is not null then raise exception 'match ended' using errcode = 'check_violation'; end if;
  if r > 0 and not round_done(m.id, r - 1) then raise exception 'round locked' using errcode = 'check_violation'; end if;
  insert into match_answers (match_id, user_id, question_key, answer)
    values (m.id, auth.uid(), answer_question.question_key, trim(answer))
    on conflict do nothing;
  perform beta_answer(m, other, answer_question.question_key);
end $$;

create function send_message(other uuid, body text) returns void
language plpgsql security definer set search_path = public as $$
declare m matches := match_with(other);
begin
  if m.ended_at is not null or not chat_open(m.id) then raise exception 'chat closed' using errcode = 'check_violation'; end if;
  insert into messages (match_id, sender_id, body) values (m.id, auth.uid(), trim(body));
  perform beta_reply(m, other);
end $$;

create function propose_date(other uuid, idea text, place text, when_text text, reserved boolean) returns void
language plpgsql security definer set search_path = public as $$
declare m matches := match_with(other);
begin
  if m.ended_at is not null or not chat_open(m.id) then raise exception 'chat closed' using errcode = 'check_violation'; end if;
  insert into match_dates (match_id, proposed_by, idea, place, when_text, reserved)
    values (m.id, auth.uid(), idea, place, when_text, reserved)
    on conflict (match_id) do update set proposed_by = excluded.proposed_by, idea = excluded.idea, place = excluded.place,
      when_text = excluded.when_text, reserved = excluded.reserved, accepted = false, past = false;
  perform beta_accept_date(m, other);
end $$;

-- Zusagen kann nur, wer den Vorschlag bekommen hat.
create function accept_date(other uuid) returns void
language sql security definer set search_path = public as $$
  update match_dates set accepted = true
  where match_id = (match_with(other)).id and proposed_by = other
$$;

create function answer_after_date(other uuid, answer text) returns void
language plpgsql security definer set search_path = public as $$
declare m matches := match_with(other);
begin
  if not exists (select from match_dates where match_id = m.id and past) then
    raise exception 'date not over' using errcode = 'check_violation';
  end if;
  insert into after_date (match_id, user_id, answer) values (m.id, auth.uid(), answer) on conflict do nothing;
  perform beta_after_date(m, other);
end $$;

create function end_match(other uuid, goodbye text) returns void
language plpgsql security definer set search_path = public as $$
declare m matches := match_with(other);
begin
  if m.ended_at is not null then return; end if;
  insert into messages (match_id, sender_id, body) values (m.id, auth.uid(), trim(goodbye));
  update matches set ended_at = now(), ended_by = auth.uid() where id = m.id;
end $$;

-- Testbetrieb (Beta) ---------------------------------------------------------
-- Solange beta_settings.enabled gilt: SMS- und Ausweisprüfung lassen sich überspringen, und die
-- Beispielprofile (is_sample) antworten selbst, damit man die App allein durchspielen kann.
-- Vor dem echten Start abschalten: update beta_settings set enabled = false;

create table beta_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default false
);
insert into beta_settings default values;
alter table beta_settings enable row level security;
revoke all on beta_settings from anon, authenticated;

alter table profiles add column is_sample boolean not null default false;

create function beta_enabled() returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select enabled from beta_settings), false)
$$;

create or replace function has_confirmed_phone() returns boolean
language sql stable security definer set search_path = '' as $$
  select public.beta_enabled()
      or exists (select from auth.users u where u.id = auth.uid() and u.phone_confirmed_at is not null)
$$;

-- Statt der Ausweisprüfung: als geprüft eintragen und im nächstgelegenen Gebiet zulassen.
create function beta_verify() returns void
language plpgsql security definer set search_path = public as $$
declare me profiles;
begin
  if not beta_enabled() then raise exception 'beta disabled' using errcode = 'insufficient_privilege'; end if;
  select * into me from profiles where id = auth.uid();
  if me.id is null then raise exception 'no profile' using errcode = 'check_violation'; end if;
  insert into verifications (user_id, provider, provider_ref, id_check, selfie_match, decided_at)
    values (me.id, 'beta', 'beta', 'passed', 'passed', now()) on conflict do nothing;
  update profiles set status = 'admitted',
    area_id = (select id from areas order by distance_km(me.lat, me.lng, lat, lng) limit 1)
  where id = me.id and status = 'pending_verification';
end $$;

-- Beispielprofile bleiben aktiv, solange jemand die Beta benutzt.
create or replace function touch_activity() returns void
language sql security definer set search_path = public as $$
  update profiles set last_active_at = now() where id = auth.uid() or (is_sample and beta_enabled())
$$;

create function beta_bot(other uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select beta_enabled() and exists (select from profiles where id = other and is_sample)
$$;

create function beta_answer(m matches, other uuid, question_key text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not beta_bot(other) then return; end if;
  insert into match_answers (match_id, user_id, question_key, answer) values (m.id, other, question_key,
    case question_key
      when '0-0' then case when (select jsonb_array_length(prompts) > 0 from profiles where id = other)
        then 'Ich habe deine Antworten gelesen und hatte sofort Fragen. Die erste: Wie bist du darauf gekommen?'
        else 'Ausschlafen, Markt, abends mit Freunden kochen.' end
      when '0-1' then 'Heute Morgen unter der Dusche.'
      when '1-0' then 'Für meine Schwester.'
      when '1-1' then 'Nein sagen, ohne mich zu rechtfertigen.'
      when '2-0' then 'Jemand, bei dem ich nichts erklären muss.'
      else 'Der Sommer, in dem ich schwimmen gelernt habe.'
    end) on conflict do nothing;
end $$;

create function beta_reply(m matches, other uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  replies text[] := array[
    'Haha, genau so! Erzähl mir mehr 🙂',
    'Das klingt gut. Was machst du eigentlich, wenn du nicht in der Uni bist?',
    'Ich muss gleich los, aber ich melde mich heute Abend!',
    'Okay, jetzt bin ich neugierig. Wollen wir das bei einem Kaffee weiterbesprechen?'];
  n int;
begin
  if not beta_bot(other) then return; end if;
  select count(*) into n from messages where match_id = m.id and sender_id = other;
  insert into messages (match_id, sender_id, body, created_at)
    values (m.id, other, replies[n % array_length(replies, 1) + 1], now() + interval '1 second');
end $$;

create function beta_accept_date(m matches, other uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not beta_bot(other) then return; end if;
  update match_dates set accepted = true where match_id = m.id;
  insert into messages (match_id, sender_id, body, created_at)
    select m.id, other, when_text || ' passt mir super. Bis dann!', now() + interval '1 second'
    from match_dates where match_id = m.id;
end $$;

create function beta_after_date(m matches, other uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  if beta_bot(other) then
    insert into after_date (match_id, user_id, answer) values (m.id, other, 'yes') on conflict do nothing;
  end if;
end $$;

-- Nur im Test: ein Date sofort als vorbei markieren, um den Check danach auszuprobieren.
create function beta_finish_date(other uuid) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not beta_enabled() then raise exception 'beta disabled' using errcode = 'insufficient_privilege'; end if;
  update match_dates set past = true where match_id = (match_with(other)).id and accepted;
end $$;

-- Testkonto auf Anfang: Likes und Matches mit Beispielprofilen weg, dann
-- 3 Beispielprofile, die schon geliked haben (ein Like zurück ist ein Match),
-- ein Match mit offenem Chat und eins, bei dem die Fragenrunde beginnt.
create function beta_prepare_tester(tester uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  me profiles;
  pool uuid[];
  yesterday timestamptz := now() - interval '1 day';
  chat_match bigint;
  k text;
begin
  if not beta_enabled() then raise exception 'beta disabled' using errcode = 'insufficient_privilege'; end if;
  select * into me from profiles where id = tester;
  delete from matches where (user_a = tester and user_b in (select id from profiles where is_sample))
                         or (user_b = tester and user_a in (select id from profiles where is_sample));
  delete from likes where (from_id = tester and to_id in (select id from profiles where is_sample))
                       or (to_id = tester and from_id in (select id from profiles where is_sample));

  select array_agg(id order by display_name) into pool from profiles
  where is_sample and gender = any(me.seeking) and me.gender = any(seeking);
  if coalesce(array_length(pool, 1), 0) < 5 then return; end if;

  -- Fans: tauchen in den Vorschlägen auf, ein Like ergibt sofort ein Match.
  insert into likes (from_id, to_id, decision, created_at)
    select unnest(pool[3:5]), tester, 'like', yesterday;

  -- Zwei fertige Matches (Likes von gestern zählen nicht zu den 6 von heute).
  insert into likes (from_id, to_id, decision, created_at) values
    (pool[1], tester, 'like', yesterday), (pool[2], tester, 'like', yesterday),
    (tester, pool[1], 'like', yesterday), (tester, pool[2], 'like', yesterday);
  update matches set created_at = yesterday
    where user_a = least(tester, pool[1]) and user_b = greatest(tester, pool[1]) returning id into chat_match;

  foreach k in array array['0-0', '0-1', '1-0', '1-1', '2-0', '2-1'] loop
    insert into match_answers (match_id, user_id, question_key, answer, created_at) values
      (chat_match, tester, k, 'Meine Antwort aus dem Test.', yesterday),
      (chat_match, pool[1], k, 'Ihre Antwort aus dem Test: ehrlich, kurz und ein bisschen neugierig.', yesterday);
  end loop;
  insert into messages (match_id, sender_id, body, created_at) values
    (chat_match, tester, 'Deine Antwort zur Freundschaft hat mich echt berührt.', yesterday),
    (chat_match, pool[1], 'Danke! Hast du am Wochenende Zeit für einen Kaffee?', yesterday + interval '2 hours');
end $$;

create function beta_reset_me() returns void
language sql security definer set search_path = public as $$
  select beta_prepare_tester(auth.uid())
$$;

-- Rechte -------------------------------------------------------------------

revoke execute on function match_with, round_done, chat_open, my_matches, answer_question, send_message, propose_date,
  accept_date, answer_after_date, end_match, beta_enabled, beta_verify, beta_bot, beta_answer, beta_reply,
  beta_accept_date, beta_after_date, beta_finish_date, beta_prepare_tester, beta_reset_me from public;

grant execute on function my_matches, answer_question, send_message, propose_date, accept_date, answer_after_date,
  end_match, beta_verify, beta_finish_date, beta_reset_me to authenticated;
-- Die App fragt schon vor der Anmeldung, ob der Testbetrieb läuft.
grant execute on function beta_enabled to anon, authenticated;
grant execute on function beta_prepare_tester to service_role;
