-- Treffen auf dem Server (Regeln wie src/domain/events.ts): kleine Events im eigenen Gebiet, Plätze je zur
-- Hälfte für Frauen und Männer, Gruppenchat für alle, die dabei sind, nach dem Event Sterne und
-- „Wen möchtest du wiedersehen?“; nur gegenseitige Wünsche werden zu Matches.
-- Die App liest über my_events() und schreibt nur über die Funktionen unten.
-- Noch nicht auf dem Server: Echt Plus (früher anmelden, Rabatt), Campus-Bestätigung, Nicht-Erscheinen.

create table events (
  id bigint generated by default as identity primary key,
  host_id uuid not null references profiles on delete cascade,
  area_id bigint not null references areas,
  title text not null check (length(trim(title)) between 3 and 80),
  kind text not null check (kind in ('Feiern', 'Essen & Trinken', 'Sport', 'Spiele', 'Kultur', 'Draußen')),
  place text not null check (length(trim(place)) between 1 and 120),
  when_text text not null,
  starts_at timestamptz not null,
  seats int not null,
  price numeric(5, 2) not null default 0 check (price between 0 and 50),
  access text not null default 'open' check (access in ('open', 'invite')),
  campus text,
  tonight boolean not null default false,
  created_at timestamptz not null default now(),
  check (case when tonight then seats in (4, 6, 8) and price = 0 else seats in (8, 10, 12) end)
);
create index events_area on events (area_id, starts_at);

create table event_attendees (
  event_id bigint not null references events on delete cascade,
  user_id uuid not null references profiles on delete cascade,
  gender text not null check (gender in ('f', 'm')),
  joined_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create table event_invites (
  event_id bigint not null references events on delete cascade,
  user_id uuid not null references profiles on delete cascade,
  primary key (event_id, user_id)
);

create table event_messages (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events on delete cascade,
  sender_id uuid not null references profiles on delete cascade,
  body text not null check (length(trim(body)) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index event_messages_event on event_messages (event_id, created_at);

create table event_reviews (
  event_id bigint not null references events on delete cascade,
  user_id uuid not null references profiles on delete cascade,
  stars int not null check (stars between 1 and 5),
  body text not null default '',
  created_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

-- „Wiedersehen“-Wünsche bleiben verborgen; gegenseitige werden zu Matches.
create table event_wishes (
  event_id bigint not null references events on delete cascade,
  from_id uuid not null references profiles on delete cascade,
  to_id uuid not null references profiles on delete cascade,
  primary key (event_id, from_id, to_id),
  check (from_id <> to_id)
);

alter table events enable row level security;
alter table event_attendees enable row level security;
alter table event_invites enable row level security;
alter table event_messages enable row level security;
alter table event_reviews enable row level security;
alter table event_wishes enable row level security;
revoke all on events, event_attendees, event_invites, event_messages, event_reviews, event_wishes from anon, authenticated;

-- Ein Event gilt 3 Stunden nach Beginn als vorbei; danach kommt der Rückblick.
create function event_over(e events) returns boolean
language sql stable as $$ select e.starts_at + interval '3 hours' < now() $$;

-- „Heute, 21:00 Uhr“, „Morgen, 12:30 Uhr“ oder „Samstag, 14:00 Uhr“ (deutsche Zeit).
create function event_when_label(ts timestamptz) returns text
language sql stable as $$
  select case (ts at time zone 'Europe/Berlin')::date - (now() at time zone 'Europe/Berlin')::date
           when 0 then 'Heute' when 1 then 'Morgen'
           else (array['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'])
                  [extract(dow from ts at time zone 'Europe/Berlin')::int + 1]
         end || ', ' || to_char(ts at time zone 'Europe/Berlin', 'HH24:MI') || ' Uhr'
$$;

-- Das Event, wenn ich es sehen darf: eigenes Gebiet und niemand hat den anderen blockiert.
create function event_for_me(p_event bigint) returns events
language plpgsql stable security definer set search_path = public as $$
declare e events;
begin
  select ev.* into e from events ev join profiles me on me.id = auth.uid()
  where ev.id = p_event and ev.area_id = me.area_id and me.status = 'admitted'
    and not blocked_between(auth.uid(), ev.host_id);
  if e.id is null then raise exception 'no event' using errcode = 'insufficient_privilege'; end if;
  return e;
end $$;

create function event_people(p_event bigint) returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(jsonb_build_object('id', p.id, 'name', p.display_name,
           'age', date_part('year', age(p.birthdate))::int, 'gender', a.gender) order by a.joined_at), '[]')
  from event_attendees a join profiles p on p.id = a.user_id
  where a.event_id = p_event and a.user_id <> auth.uid()
$$;

create function event_host(p_host uuid) returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'name', (select display_name from profiles where id = p_host),
    'events', (select count(*) from events e where e.host_id = p_host and event_over(e)),
    'ratings', (select coalesce(jsonb_agg(r.stars), '[]') from event_reviews r join events e on e.id = r.event_id
                where e.host_id = p_host and r.user_id <> p_host),
    'reviews', (select coalesce(jsonb_agg(body order by created_at desc), '[]') from (
                  select r.body, r.created_at from event_reviews r join events e on e.id = r.event_id
                  where e.host_id = p_host and r.user_id <> p_host and r.body <> ''
                  order by r.created_at desc limit 3) x))
$$;

-- Lesen ----------------------------------------------------------------------

-- Kommende Events im eigenen Gebiet, dazu meine vergangenen der letzten 14 Tage für den Rückblick.
-- Teilnehmende und Gruppenchat sieht nur, wer dabei ist; Eingeladene nur der Gastgeber.
create function my_events() returns jsonb
language sql stable security definer set search_path = public as $$
  with me as (select * from profiles where id = auth.uid() and status = 'admitted')
  select jsonb_build_object(
    'events', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', e.id::text, 'title', e.title, 'kind', e.kind, 'when', e.when_text, 'starts_at', e.starts_at,
        'place', e.place, 'seats', e.seats, 'price', e.price, 'access', e.access, 'campus', e.campus, 'tonight', e.tonight,
        'joined', jsonb_build_object(
          'f', (select count(*) from event_attendees where event_id = e.id and gender = 'f'),
          'm', (select count(*) from event_attendees where event_id = e.id and gender = 'm')),
        'host', event_host(e.host_id),
        'is_host', e.host_id = me.id,
        'mine', exists (select from event_attendees where event_id = e.id and user_id = me.id),
        'invited', exists (select from event_invites where event_id = e.id and user_id = me.id),
        'invitees', case when e.host_id = me.id then (
          select coalesce(jsonb_agg(p.display_name), '[]') from event_invites i join profiles p on p.id = i.user_id
          where i.event_id = e.id) end,
        'people', case when exists (select from event_attendees where event_id = e.id and user_id = me.id)
          then event_people(e.id) end,
        'messages', case when exists (select from event_attendees where event_id = e.id and user_id = me.id) then (
          select coalesce(jsonb_agg(jsonb_build_object('id', m.id, 'mine', m.sender_id = me.id, 'name', p.display_name,
                   'text', m.body, 'at', m.created_at) order by m.created_at, m.id), '[]')
          from event_messages m join profiles p on p.id = m.sender_id where m.event_id = e.id) end
      ) order by e.tonight desc, e.starts_at), '[]')
      from events e, me
      where e.area_id = me.area_id and not event_over(e) and not blocked_between(me.id, e.host_id)),
    'past', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id', e.id::text, 'title', e.title, 'when', e.when_text, 'place', e.place,
        'host', (select display_name from profiles where id = e.host_id),
        'attendees', event_people(e.id),
        'review', (select jsonb_build_object('stars', r.stars, 'text', r.body, 'mutual', (
                     select coalesce(jsonb_agg(w.to_id), '[]') from event_wishes w
                     where w.event_id = e.id and w.from_id = auth.uid()
                       and exists (select from event_wishes back where back.event_id = e.id and back.from_id = w.to_id and back.to_id = auth.uid())))
                   from event_reviews r where r.event_id = e.id and r.user_id = auth.uid())
      ) order by e.starts_at desc), '[]')
      from events e join event_attendees a on a.event_id = e.id and a.user_id = auth.uid()
      where event_over(e) and e.starts_at > now() - interval '14 days')
  )
$$;

-- Schreiben --------------------------------------------------------------------

create function create_event(title text, kind text, place text, when_text text, starts_at timestamptz, seats int,
                             price numeric, access text, campus text, tonight boolean, invitees uuid[]) returns text
language plpgsql security definer set search_path = public as $$
declare
  me profiles;
  new_id bigint;
begin
  select * into me from profiles where id = auth.uid() and status = 'admitted';
  if me.id is null then raise exception 'not admitted' using errcode = 'insufficient_privilege'; end if;
  if starts_at < now() - interval '1 hour' or starts_at > now() + interval '60 days' then
    raise exception 'bad time' using errcode = 'check_violation';
  end if;
  insert into events (host_id, area_id, title, kind, place, when_text, starts_at, seats, price, access, campus, tonight)
    values (me.id, me.area_id, trim(title), kind, trim(place), when_text, starts_at, seats, price, access, campus, tonight)
    returning id into new_id;
  insert into event_attendees (event_id, user_id, gender) values (new_id, me.id, me.gender);
  -- Einladen kann man nur eigene Matches.
  insert into event_invites (event_id, user_id)
    select new_id, u from unnest(coalesce(invitees, '{}')) u
    where exists (select from matches where user_a = least(me.id, u) and user_b = greatest(me.id, u))
      and not blocked_between(me.id, u)
    on conflict do nothing;
  return new_id::text;
end $$;

-- Ein Platz in der eigenen Hälfte; die Sperre auf dem Event verhindert, dass zwei gleichzeitig den letzten nehmen.
create function join_event(event_id text) returns void
language plpgsql security definer set search_path = public as $$
declare
  e events := event_for_me(event_id::bigint);
  g text := (select gender from profiles where id = auth.uid());
begin
  perform from events where id = e.id for update;
  if event_over(e) then raise exception 'event over' using errcode = 'check_violation'; end if;
  if exists (select from event_attendees a where a.event_id = e.id and a.user_id = auth.uid()) then return; end if;
  if e.access = 'invite' and not exists (select from event_invites i where i.event_id = e.id and i.user_id = auth.uid()) then
    raise exception 'invite only' using errcode = 'insufficient_privilege';
  end if;
  if (select count(*) from event_attendees a where a.event_id = e.id and a.gender = g) >= e.seats / 2 then
    raise exception 'full' using errcode = 'check_violation';
  end if;
  insert into event_attendees (event_id, user_id, gender) values (e.id, auth.uid(), g);
end $$;

-- Der Gastgeber bleibt dabei; alle anderen können absagen, solange das Event nicht vorbei ist.
create function leave_event(event_id text) returns void
language plpgsql security definer set search_path = public as $$
declare e events := event_for_me(event_id::bigint);
begin
  if e.host_id = auth.uid() then raise exception 'host stays' using errcode = 'check_violation'; end if;
  delete from event_attendees a where a.event_id = e.id and a.user_id = auth.uid() and not event_over(e);
end $$;

create function send_event_message(event_id text, body text) returns void
language plpgsql security definer set search_path = public as $$
declare e events := event_for_me(event_id::bigint);
begin
  if not exists (select from event_attendees a where a.event_id = e.id and a.user_id = auth.uid()) then
    raise exception 'not attending' using errcode = 'insufficient_privilege';
  end if;
  insert into event_messages (event_id, sender_id, body) values (e.id, auth.uid(), trim(body));
  -- Testbetrieb: Gastgeber aus den Beispielprofilen antworten einmal.
  if beta_bot(e.host_id) and not exists (select from event_messages m where m.event_id = e.id and m.sender_id = e.host_id) then
    insert into event_messages (event_id, sender_id, body, created_at)
      values (e.id, e.host_id, 'Schön, dass du dabei bist! Ich warte am Treffpunkt, ihr erkennt mich an der roten Jacke 🙂', now() + interval '1 second');
  end if;
end $$;

-- Sterne, ein Satz und Wiedersehen-Wünsche, einmal pro Event. Gibt die gegenseitigen Wünsche zurück;
-- daraus werden Matches (mit Fragenrunde wie nach einem Like).
create function review_event(event_id text, stars int, body text, picks uuid[]) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  e events;
  mutual uuid[];
  u uuid;
begin
  select * into e from events where id = event_id::bigint;
  if e.id is null or not exists (select from event_attendees a where a.event_id = e.id and a.user_id = auth.uid()) then
    raise exception 'not attending' using errcode = 'insufficient_privilege';
  end if;
  if not event_over(e) then raise exception 'event not over' using errcode = 'check_violation'; end if;
  insert into event_reviews (event_id, user_id, stars, body) values (e.id, auth.uid(), stars, trim(coalesce(body, '')));
  insert into event_wishes (event_id, from_id, to_id)
    select e.id, auth.uid(), p from unnest(coalesce(picks, '{}')) p
    where exists (select from event_attendees a where a.event_id = e.id and a.user_id = p)
    on conflict do nothing;
  select coalesce(array_agg(w.to_id), '{}') into mutual from event_wishes w
  where w.event_id = e.id and w.from_id = auth.uid()
    and exists (select from event_wishes back where back.event_id = e.id and back.from_id = w.to_id and back.to_id = auth.uid())
    and not blocked_between(auth.uid(), w.to_id);
  foreach u in array mutual loop
    insert into matches (user_a, user_b) values (least(auth.uid(), u), greatest(auth.uid(), u)) on conflict do nothing;
  end loop;
  return to_jsonb(mutual);
end $$;

-- Testbetrieb ----------------------------------------------------------------------
-- Events der Beispielprofile neu anlegen: einer für heute Abend, drei in den nächsten Tagen und ein
-- vergangener Brettspielabend mit der Testperson, bei dem zwei sie wiedersehen möchten.
create function beta_prepare_events(tester uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  me profiles;
  same uuid[];
  other uuid[];
  host_f uuid;
  host_m uuid;
  tonight_at timestamptz := date_trunc('hour', now()) + interval '3 hours';
  tomorrow date := (now() at time zone 'Europe/Berlin')::date + 1;
  past_id bigint;
  ev bigint;
begin
  if not beta_enabled() then raise exception 'beta disabled' using errcode = 'insufficient_privilege'; end if;
  select * into me from profiles where id = tester;
  -- Kommende Events der Beispielprofile gelten für alle, vergangene nur für die jeweilige Testperson.
  delete from events e where e.host_id in (select id from profiles where is_sample)
    and (not event_over(e) or exists (select from event_attendees a where a.event_id = e.id and a.user_id = tester));
  select array_agg(id order by display_name) into same from profiles where is_sample and gender = me.gender and area_id = me.area_id;
  select array_agg(id order by display_name) into other from profiles where is_sample and gender <> me.gender and area_id = me.area_id;
  if coalesce(array_length(same, 1), 0) < 4 or coalesce(array_length(other, 1), 0) < 6 then return; end if;
  host_f := case when me.gender = 'f' then same[1] else other[1] end;
  host_m := case when me.gender = 'm' then same[1] else other[1] end;

  insert into events (host_id, area_id, title, kind, place, when_text, starts_at, seats, tonight)
    values (host_f, me.area_id, 'Kneipentour, wer kommt mit?', 'Feiern', 'Start an der Bar am Seltersweg',
            event_when_label(tonight_at), tonight_at, 8, true) returning id into ev;
  insert into event_attendees (event_id, user_id, gender) select ev, id, gender from profiles
    where id in (host_f, other[2], same[2]) on conflict do nothing;

  insert into events (host_id, area_id, title, kind, place, when_text, starts_at, seats)
    values (host_m, me.area_id, 'Pub-Quiz mit Fremden', 'Spiele', 'Irish Pub am Kirchenplatz',
            event_when_label((tomorrow + time '19:30') at time zone 'Europe/Berlin'), (tomorrow + time '19:30') at time zone 'Europe/Berlin', 12)
    returning id into ev;
  insert into event_attendees (event_id, user_id, gender) select ev, id, gender from profiles
    where id in (host_m, other[3], other[4], same[3]) on conflict do nothing;

  insert into events (host_id, area_id, title, kind, place, when_text, starts_at, seats, campus)
    values (host_f, me.area_id, 'Mittag in der Mensa mit Fremden', 'Essen & Trinken', 'Mensa Otto-Behaghel-Straße, Tisch mit Echt-Schild',
            event_when_label((tomorrow + time '12:30') at time zone 'Europe/Berlin'), (tomorrow + time '12:30') at time zone 'Europe/Berlin', 8, 'JLU Gießen')
    returning id into ev;
  insert into event_attendees (event_id, user_id, gender) select ev, id, gender from profiles
    where id in (host_f, other[5]) on conflict do nothing;

  insert into events (host_id, area_id, title, kind, place, when_text, starts_at, seats, price)
    values (host_m, me.area_id, 'Bouldern für Anfänger', 'Sport', 'Boulderhalle in der Weststadt',
            event_when_label((tomorrow + 2 + time '14:00') at time zone 'Europe/Berlin'), (tomorrow + 2 + time '14:00') at time zone 'Europe/Berlin', 8, 12)
    returning id into ev;
  insert into event_attendees (event_id, user_id, gender) select ev, id, gender from profiles
    where id in (host_m, same[4]) on conflict do nothing;

  insert into events (host_id, area_id, title, kind, place, when_text, starts_at, seats, created_at)
    values (host_m, me.area_id, 'Brettspielabend', 'Spiele', 'Spielecafé in der Innenstadt', 'Vorgestern, 19:00 Uhr',
            now() - interval '2 days', 10, now() - interval '5 days')
    returning id into past_id;
  insert into event_attendees (event_id, user_id, gender) select past_id, id, gender from profiles
    where id in (tester, host_m, same[2], same[3], other[2], other[3], other[4]) on conflict do nothing;
  insert into event_wishes (event_id, from_id, to_id) values (past_id, other[2], tester), (past_id, other[3], tester);
  insert into event_reviews (event_id, user_id, stars, body) values
    (past_id, other[4], 5, 'Lockere Runde, alle wurden gut eingebunden.'),
    (past_id, same[2], 4, 'Schwere Fragen, aber super Stimmung.');
end $$;

create or replace function beta_reset_me() returns void
language plpgsql security definer set search_path = public as $$
begin
  if not beta_enabled() then raise exception 'beta disabled' using errcode = 'insufficient_privilege'; end if;
  delete from blocks where (blocker_id = auth.uid() and blocked_id in (select id from profiles where is_sample))
                        or (blocked_id = auth.uid() and blocker_id in (select id from profiles where is_sample));
  delete from reports where reporter_id = auth.uid() and reported_id in (select id from profiles where is_sample);
  delete from events where host_id = auth.uid();
  perform beta_prepare_tester(auth.uid());
  perform beta_prepare_events(auth.uid());
end $$;

revoke execute on function event_over, event_when_label, event_for_me, event_people, event_host, my_events, create_event,
  join_event, leave_event, send_event_message, review_event, beta_prepare_events from public;
grant execute on function my_events, create_event, join_event, leave_event, send_event_message, review_event to authenticated;
grant execute on function beta_prepare_events to service_role;
